name: BMW RAG Capstone CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-and-quality:
    name: Build, Test & Quality Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linting (Flake8)
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Run Security Analysis (Bandit)
        run: |
          bandit -r src -ll -ii

      - name: Run Pytest & Generate Coverage Report
        env:
          OLLAMA_BASE_URL: "http://localhost:11434"
          OLLAMA_MODEL: "qwen2.5:1.5b"
        run: |
          pytest --cov=src --cov-report=term-missing --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

            - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build . -t deepakkumar889/bmw-service-rag:latest
          docker push deepakkumar889/bmw-service-rag:latest